"""rename avatar_url to photoUrl

Revision ID: cb429282ce4b
Revises: 9471beab72d9
Create Date: 2025-01-22 20:54:12.560193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb429282ce4b'
down_revision = '9471beab72d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photoUrl', sa.String(length=255), nullable=True))
        batch_op.drop_column('avatar_url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_url', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('photoUrl')

    # ### end Alembic commands ###
